import type { MJMLParsingOptions } from 'mjml-core'
import type { Options } from 'html-minifier'

export const BUILD_DIRECTORY_NAME = './dist'
export const PUBLIC_DIRECTORY_NAME = './public'
export const TEMPLATES_DIRECTORY_NAME = './src/templates'

// see `README.md` for details
export const TEMPLATE_VARIABLE_BY_NAME = {
  // common
  appLink: 'https://app.example.com',
  supportTelegram: 'support',
  supportEmail: 'support@example.com',
  firstName: 'Billy',
  userEmail: 'herrington@example.com',
  companyName: 'Gachi LTD',
  link: 'https://app.example.com/api/verify/email?code=69',
  // colors
  colorTextDefault: '#1A1A1A',
  colorTextDescription: '#6B7780',
  colorTextBrand: '#219b61',
  colorTextBrandDark: '#176B44',
  colorTextLink: '#1B7F4C',
  colorTextButton: '#FFFFFF',
  colorBgDefault: '#FFFFFF',
  colorBgBrand: '#219b61',
  colorBgButtonBrand: '#219b61',
  colorBorderDefault: '#D0E4DA',
  // icons
  logoUrl: '../src/assets/images/common/logo.png',
  emailIconUrl: '../src/assets/images/common/emailIconUrl.png',
  telegramLogoUrl: '../src/assets/images/common/telegramLogoUrl.png',
  subjectPasswordIconUrl: '../src/assets/images/subject/subjectPasswordIconUrl.png',
  subjectSecurityIconUrl: '../src/assets/images/subject/subjectSecurityIconUrl.png',
  subjectEmailIconUrl: '../src/assets/images/subject/subjectEmailIconUrl.png',
  subjectWelcomeIconUrl: '../src/assets/images/subject/subjectWelcomeIconUrl.png',
}

// https://documentation.mjml.io/#inside-node-js
export const MJML_OPTIONS: MJMLParsingOptions = {
  // Full path of the specified file to use when resolving paths from mj-include components
  filePath: './src/common/header', // mjml can't resolve path, so this is just a depth for the resolution
}

// https://github.com/kangax/html-minifier?tab=readme-ov-file#options-quick-reference
export const HTML_MINIFIER_OPTIONS: Options = {
  caseSensitive: false,
  collapseBooleanAttributes: false,
  collapseInlineTagWhitespace: false,
  collapseWhitespace: true,
  conservativeCollapse: false,
  decodeEntities: true,
  html5: true,
  includeAutoGeneratedTags: false,
  keepClosingSlash: false,
  maxLineLength: undefined,
  minifyCSS: false, // never set to true, that will break the generation
  minifyJS: true,
  preserveLineBreaks: false,
  preventAttributesEscaping: false,
  processConditionalComments: false,
  removeAttributeQuotes: false, // leave false, since space could occur in {{variables}}
  removeComments: false,
  removeEmptyAttributes: false,
  removeOptionalTags: false,
  removeRedundantAttributes: false,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  removeTagWhitespace: false,
  sortAttributes: false,
  sortClassName: false,
  trimCustomFragments: true,
  useShortDoctype: true,
}
